image:
  tag: sha-7ef043ae2801dd53575a5d6ef148d8d693766df8

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1024Mi

autoscaling:
  enabled: true

mysql:
  primary:
    persistence:
      enabled: true
