frontend:
  image:
    tag: sha-24cf6062c929c656364efd2ab348d7992e55f19c
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  ingress:
    enabled: true
  autoscaling:
    enabled: true
backend:
  image:
    tag: sha-7ef043ae2801dd53575a5d6ef148d8d693766df8
  db:
    host: db
    name: appdb
    username: appuser
    password: appsecret
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1024Mi
  autoscaling:
    enabled: true
mysql:
  fullnameOverride: db
  auth:
    database: appdb
    username: appuser
    password: appsecret
    rootPassword: rootpassword
  primary:
    persistence:
      enabled: true
      size: 32Gi
