apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app.kubernetes.io/instance: three-tier-app
    app.kubernetes.io/name: backend
    app.kubernetes.io/component: backend
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/part-of: three-tier-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: three-tier-app
        app.kubernetes.io/name: backend
        app.kubernetes.io/component: backend
        app.kubernetes.io/version: 1.0.0
        app.kubernetes.io/part-of: three-tier-app
    spec:
      containers:
      - name: backend
        image: ghcr.io/hasanashab/spring-react-devops-backend:latest
        env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://db:3306/hobbie_backend_db_prod?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Paris
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
        ports:
        - containerPort: 8080
