apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app.kubernetes.io/instance: three-tier-app
    app.kubernetes.io/name: backend
    app.kubernetes.io/component: backend
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/part-of: three-tier-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: three-tier-app
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: three-tier-app
        app.kubernetes.io/name: backend
        app.kubernetes.io/component: backend
        app.kubernetes.io/version: 1.0.0
        app.kubernetes.io/part-of: three-tier-app
    spec:
      containers:
      - name: backend
        image: ghcr.io/hasanashab/spring-react-devops-backend:latest
        ports:
        - containerPort: 8080
