apiVersion: v2
name: three-tier-app
description: Plugged helm chart for local testing
type: application
version: "0.1.0"
appVersion: "1.0.0"
dependencies:
  - name: frontend
    version: 0.1.0
    repository: "file://../frontend"
  - name: backend
    version: 0.1.0
    repository: "file://../backend"