frontend:
  image:
    tag: "sha-84752cfa249ecf78f75f7e79f9c9af098c2dc9cc"
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  ingress:
    enabled: true
  autoscaling:
    enabled: true

backend:
  image:
    tag: "sha-cc42d1e083e7dd15fc8305f948148a43a4d3f549"
  db:
    host: db
    name: appdb
    username: appuser
    password: appsecret
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1024Mi
  autoscaling:
    enabled: true

mysql:
  fullnameOverride: db
  auth:
    database: appdb
    username: appuser
    password: appsecret
    rootPassword: rootpassword
  primary:
    persistence:
      enabled: true
      size: 32Gi