replicaCount: 1

image:
  repository: ghcr.io/hasanashab/spring-react-devops-eks-backend
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "backend"

serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}

podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1002
  runAsGroup: 1002
  # capabilities:
  #   drop:
  #   - ALL

service:
  type: ClusterIP
  port: 8080

resources: {}

# livenessProbe:
#   httpGet:
#     path: /
#     port: http
# readinessProbe:
#   httpGet:
#     path: /
#     port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}

db:
  host: ""
  name: ""
  username: ""
  password: ""
  port: 3306
  createDatabaseIfNotExist: true
  useSSL: false
  allowPublicKeyRetrieval: true
  useJDBCCompliantTimezoneShift: true
  useUnicode: true
  useLegacyDatetimeCode: false
  serverTimezone: "Europe/Paris"
